### ISSUE TITLE
listObject 死循环

### ISSUE THREAD

**Issue by ric-z** [ks3sdk/ks3-java-sdk#2]
以下代码 nextMarker  返回值总是为 null。

      ObjectListing list = null;
      list = client.listObjects(request);
      String nextMarker = list.getNextMarker();

**Comment by demiks** [comment]
多谢！ 这么修改已经修复该问题。不过这样设计貌似有点反直觉啊。。。

**Comment by void-main** [comment]
@ric-z 确实不太直观，我们也意识到了这个问题，但是接口已经公布出去了，不太好调整；只能在文档里面多加些说明了。谢谢！
